inherit_from: .rubocop_todo.yml

# Offense count: 147
# Configuration parameters: AllowedChars.
Style/AsciiComments:
  Enabled: false


# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: Strict.
Style/NumericLiterals:
  Enabled: false

# Offense count: 90
# Configuration parameters: CountComments, ExcludedMethods.
# ExcludedMethods: refine
Metrics/BlockLength:
  Enabled: false

# Offense count: 4
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Enabled: false

# Offense count: 20
# Configuration parameters: CountComments, ExcludedMethods.
Metrics/MethodLength:
  Enabled: false

# Offense count: 1
Lint/IneffectiveAccessModifier:
  Enabled: true

AllCops:
  Exclude:
    - 'Gemfile*'
    - 'Rakefile'
    - 'bin/*'
    - 'config/*'
    - 'config/environments/*'
    - 'config/initializers/application_controller_renderer.rb'
    - 'config/initializers/backtrace_silencers.rb'
    - 'config/initializers/cors.rb'
    - 'config/initializers/filter_parameter_logging.rb'
    - 'config/initializers/inflections.rb'
    - 'config/initializers/wrap_parameters.rb'
    - 'config/unicorn.rb'
    - 'db/**/*'
    - 'script/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'log/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
