# use gem 'settingslogic'
defaults: &defaults
  powers:
    a:
      name: Austria
      genitive: Austrian
      jname: オーストリア
      units:
      - prov_code: vie
        type: Army
      - prov_code: bud
        type: Army
      - prov_code: tri
        type: Fleet
    e:
      name: England
      genitive: English
      jname: イギリス
      units:
      - prov_code: lvp
        type: Army
      - prov_code: lon
        type: Fleet
      - prov_code: edi
        type: Fleet
    f:
      name: France
      genitive: French
      jname: フランス
      units:
      - prov_code: par
        type: Army
      - prov_code: mar
        type: Army
      - prov_code: bre
        type: Fleet
    g:
      name: Germany
      genitive: German
      jname: ドイツ
      units:
      - prov_code: ber
        type: Army
      - prov_code: mun
        type: Army
      - prov_code: kie
        type: Fleet
    i:
      name: Italy
      genitive: Italian
      jname: イタリア
      units:
      - prov_code: rom
        type: Army
      - prov_code: ven
        type: Army
      - prov_code: nap
        type: Fleet
    r:
      name: Russia
      genitive: Russian
      jname: ロシア
      units:
      - prov_code: mos
        type: Army
      - prov_code: war
        type: Army
      - prov_code: stp_sc
        type: Fleet
      - prov_code: sev
        type: Fleet
    t:
      name: Turky
      genitive: Turkish
      jname: トルコ
      units:
      - prov_code: con
        type: Army
      - prov_code: smy
        type: Army
      - prov_code: ank
        type: Fleet
    x:
      name: Master
      jname: 管理人

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
